spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.103:8848
    gateway:
      routes:
        - id: baidu_route #http://localhost:88/?url=baidu
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: qq_route #http://localhost:88/?url=qq
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
  application:
    name: gulimall-gateway
server:
  port: 88